name: NodeJS deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Install Twilio CLI and Twilio Serverless plugin
      run: |
        npm install twilio-cli -g
        twilio plugins:install @twilio-labs/plugin-serverless

    - name: Deploy Application
      run: npm run deploy
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO.ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO.AUTH_TOKEN }}
        TWILIO_API_SECRET: ${{secrets.TWILIO.AUTH_TOKEN_SECRET}}